SERVER_URL = 'https://YOURWEBSITE.com/'
TARGET_FOLDER = 'patcher'
FILELIST_URL = f'{SERVER_URL}patcher.txt'
LOG_FILE = 'patcher.log'
DOWNLOAD_SPEED_LIMIT = 100  # KB/s
MULTITHREADING_THRESHOLD = 10485760  # bytes