@echo off
echo Starting Patcher with Tauri + Python Backend...
echo.
echo Installing Python dependencies...
pip install -r requirements.txt
echo.
echo Installing Node.js dependencies...
call npm install
echo.
echo Starting Tauri development server...
call npm run tauri dev